FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Cài SSH, XFCE4, TigerVNC
RUN apt-get update && apt-get install -y \
    openssh-server \
    xfce4 xfce4-goodies \
    tigervnc-standalone-server \
    dbus-x11 x11-xserver-utils \
    && rm -rf /var/lib/apt/lists/*

# Tạo user vncuser
RUN useradd -m -s /bin/bash vncuser && \
    echo "vncuser:123456" | chpasswd && \
    usermod -aG sudo vncuser

# Cấu hình SSH
RUN mkdir /var/run/sshd && \
    echo 'root:rootpass' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Tạo thư mục cho VNC và tạo password file
RUN mkdir -p /home/vncuser/.vnc && \
    echo "123456" | vncpasswd -f > /home/vncuser/.vnc/passwd && \
    chown -R vncuser:vncuser /home/vncuser/.vnc && \
    chmod 600 /home/vncuser/.vnc/passwd

# Copy start script
COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 22 5901

CMD ["/start.sh"]
